$schema: "http://json-schema.org/draft-06/schema#"
description: Configuration parameters for running BLR pipeline
properties:
  cluster_tag:
    type: string
    description: SAM tag to use for store barcode cluster id in bam file. 'BX' is 10x genomic default
    default: BX
  molecule_tag:
    type: string
    description: SAM flag used to store molecule ID, same as 10x default.
    default: MI
  sequence_tag:
    type: string
    description: SAM tag to use for store original barcode sequence in bam file. 'RX' is 10x genomic default
    default: RX
  phase_set_tag:
    type: string
    description: SAM tag to use for store phase set information, same as 10x default.
    default: PS
  haplotype_tag:
    type: string
    description: SAM tag to use for store haplotype information, same as 10x default.
    default: HP
  read_mapper:
    type: string
    pattern: "bwa|bowtie2|minimap2|ema"
    description: Which read mapper to use
  genome_reference:
    type: [ "string", "null" ]
    description: Reference index prefix
  dbSNP:
    type: ["string", "null" ]
    description: dbSNP, common SNP positions
  BQSR:
    type: boolean
    default: false
    description: Run gatk base score recalibration or not
  h1:
    type: string
    description: h1 adaptor sequnce, appears before barcode in read1
  h2:
    type: string
    description: h2 adaptor sequence, appears after barcode in read1
  h3:
    type: string
    description: h3 adaptor sequence, appears after genomics insert in read1 and read2.
  barcode_len:
    type: integer
    description: Length of barcode sequence
  reference_variants:
    type: [ "string", "null" ]
    description: Path to reference variants, if not provided then variant will be called by freebayes
  phasing_ground_truth:
    type: [ "string", "null" ]
    description: Path to phased variants used to compute phasing stats.
  barcode_max_dist:
    type: integer
    description: Max edit distance (Leveshtein distance) allowed to cluster two barcode sequences together
  barcode_ratio:
    type: integer
    description: Starcode parameter. Minimum difference in ratio for read count to cluster nodes
  max_molecules_per_bc:
    type: integer
    description: Max number of molecules allowed for a single barcode (removes if bc has > 260 molecules).
  variant_caller:
    type: string
    description: Which variant caller to use.
    pattern: "gatk|bcftools|freebayes|deepvariant"
  haplotag_tool:
    type: string
    description: Which haplotype tagging tool to use.
    pattern: "blr|whatshap"
  heap_space:
    type: integer
    description: Heap space to run java scripts with (gatk).
  library_type:
    type: string
    pattern: "blr|10x|stlfr"
    description: Library type.
  barcode_whitelist:
    type: [ "string", "null" ]
    description: Path to barcode whitelist for 10x linked-read demultiplexing
  apply_hamming_correction:
    type: boolean
    default: false
    description: Apply hamming correction when demultiplexing 10x barcodes. Increases runtime.
  stlfr_barcodes:
    type: ["string", "null"]
    description: Path to stLFR barcodes
  stlfr_adapter:
    type: string
    description: Adaptor sequence for stLFR constructs (from tagmentation)
  chunk_size:
    type: integer
    default: 20000000
    description: Chunk size for parallelization
  window_size:
    type: integer
    default: 30000
    description: Window size used for linking reads by barcodes.
