title: "BLR run report"
intro_text: "This is a collection of results from the BLR pipeline. Go to our
<a href=https://github.com/FrickTobias/BLR>github page</a> for more information."

custom_data:
    phasing_stats:
        id: 'phasing_stats'
        section_name: 'Phasing metrics'
        description: '- Phasing statistics from HapCUP2 calculate_phasing_stats.py script.'
        plot_type: 'table'
        pconfig:
            id: 'phasing_stats'
            title: 'Phasing metrics table'
            scale: false
            share_key: false
        headers:
            'switch rate':
                title: 'Switch rate'
                description: 'switch errors as a fraction of possible positions for switch errors'
                format: '{:,.7f}'
                placement: 1
            'mismatch rate':
                title: 'Mismatch rate'
                description: 'mismatch errors as a fraction of possible positions for mismatch errors'
                format: '{:,.7f}'
                placement: 2
            'flat rate':
                title: 'Flat rate'
                description: 'flat errors as a fraction of possible positions for flat errors'
                format: '{:,.7f}'
                hidden: true
            'phased count':
                title: 'Phased count'
                description: 'count of total SNVs phased in the test haplotype'
                format: '{:,.0f}'
                placement: 3
            AN50:
                title: 'AN50 (Mbp)'
                description: 'the AN50 metric of haplotype completeness'
                format: '{:,.3f}'
                hidden: true
            N50:
                title: 'N50 (Mbp)'
                description: 'the N50 metric of haplotype completeness'
                format: '{:,.3f}'
                placement: 4
            'num snps max blk':
                title: 'SNPs in max blk'
                description: 'the fraction of SNVs in the largest (most variants phased) block'
                format: '{:,.0f}'
                placement: 5


sp:
    phasing_stats:
        fn: 'phasing_stats.tsv'
