title: "BLR run report"
intro_text: "This is a collection of results from the BLR pipeline. Go to our
<a href=https://github.com/FrickTobias/BLR>github page</a> for more information."

extra_fn_clean_trim:
  '.phasing_stats'
