title: "BLR run report"
intro_text: "This is a collection of results from the BLR pipeline. Go to our
<a href=https://github.com/FrickTobias/BLR>github page</a> for more information."

table_columns_visible:
    mosdepth:
        30_x_pc: False
    Bowtie 2 / HiSAT2:
        overall_alignment_rate: False
    Cutadapt:
        percent_trimmed: False

extra_fn_clean_exts:
    - type: remove
      pattern: .duplicate_metrics
      module: picard

fn_ignore_dirs:
    - '.snakemake'

sp:
    picard/markdups:
      - fn: "final.duplicate_metrics.txt"
