# Whenever this file is updated, you need to run misc/condalock.sh to create
# the environment.lock.yml file.

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - python=3.6
  - dataclasses  # remove when minimum Python version is raised to 3.7
  - bowtie2>=2.4.2
  - bwa
  - minimap2
  - pysam
  - cutadapt=2.5
  - hapcut2=1.3.2
  - samtools
  - snakemake-minimal>=5.32.0  # Limit until https://github.com/snakemake/snakemake/issues/413 is solved
  - starcode
  - tqdm
  - importlib_resources
  - freebayes
  - ruamel.yaml
  - vcflib
  - ema=0.6.2
  - fastqc
  - multiqc>=1.10
  - bcftools
  - gatk4
  - pandas
  - picard-slim
  - whatshap
  - mosdepth>=0.2.9
