# Dependencies: python=3.6 cutadapt bowtie2 pysam picard=2.10 cd-hit snakemake-minimal
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - bcftools=1.9
  - bowtie2=2.3.5
  - bz2file=0.98
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cd-hit=4.8.1
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - configargparse=0.13.0
  - cryptography=2.7
  - curl=7.64.1
  - cutadapt=2.3
  - datrie=0.7.1
  - dnaio=0.3
  - docutils=0.14
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - htslib=1.9
  - idna=2.8
  - jsonschema=3.0.1
  - krb5=1.16.3
  - libcurl=7.64.1
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libdeflate=1.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libssh2=1.8.2
  - llvm-openmp=8.0.0
  - ncurses=6.1
  - openjdk=11.0.1
  - openmp=8.0.0
  - openssl=1.1.1b
  - perl=5.26.2
  - picard=2.10.6
  - pigz=2.3.4
  - pip=19.1.1
  - psutil=5.6.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyrsistent=0.15.2
  - pysam=0.15.2
  - pysocks=1.7.0
  - python=3.6.7
  - pyyaml=5.1.1
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.22.0
  - samtools=1.9
  - setuptools=41.0.1
  - six=1.12.0
  - smmap2=2.0.5
  - snakemake-minimal=5.5.0
  - sqlite=3.28.0
  - tbb=2019.7
  - tk=8.6.9
  - urllib3=1.24.3
  - wheel=0.33.4
  - wrapt=1.11.1
  - xopen=0.7.0
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - tqdm=4.32.2