# Whenever this file is updated, you need to run misc/condalock.sh to create
# the environment.lock.yml file.

channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - python=3.6
  - bowtie2
  - bwa
  - pysam
  - picard=2.10
  - cutadapt=2.5
  - samtools
  - snakemake-minimal
  - starcode
  - tqdm
  - importlib_resources
