#This code is to generate plots from the merged VCF file (max 4)
#The input VCF file should be generated by SURVIVOR and 

####
#Check and install!
list.of.packages <- c("optparse","VennDiagram","ggplot2","reshape2")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
rm(list.of.packages, new.packages)
####

library("optparse")
library("VennDiagram")

option_list = list(
  make_option(c("-i", "--input_vcf"), type="character",default="4_naibrs_merged.vcf", #NULL,
              help="merged VCF dataset input file name", metavar="character"),
  make_option(c("-o", "--out"), type="character", default=NULL, 
              help="output file name [default= %default]", metavar="character")
); 

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);



if (!is.na(opt$input_vcf)) {
  vcf_file <- opt$input_vcf
  file_name <- print(opt$input_vcf)
  file_name <- gsub('.{4}$', '_', file_name)
} else {
  stop("date parameter must be provided. See script usage (--help)")
}


#Generating comparison matrix
comparison_matrix <- sprintf("SURVIVOR genComp %s 0 comparison_matrix.txt", vcf_file)
system(comparison_matrix)

#Plot comparison matrix
t=read.table("comparison_matrix.txt",header=F)
dst <- data.matrix(t(t))
pdf(file = "figures.pdf")
# image(1:nrow(dst), 1:ncol(dst),log(dst), col=rev(heat.colors(10)),axes=F, xlab="", ylab="")
# grid(col='black',nx=nrow(dst),ny=ncol(dst),lty=1)

library(ggplot2)
library(reshape2)

tt<-data.frame(t)
tt$row <- paste("L", 1:4, sep='')
tt_melt <- melt(tt)
ggplot(data=tt_melt,
       aes(x=variable, y=row, fill=value)) + geom_tile() +
       geom_text(aes(label=value), color='white') +
       theme_bw() + scale_fill_gradient(low = "yellow", high = "red",)


dev.off()

#Get samples names
files_names <- system(sprintf("bcftools query -l %s",vcf_file),intern = T)
files_names <- sub(x = files_names, pattern = ".ema_final.naibr_sv_calls_filtered_sorted_merged.bedpe","",ignore.case = T)
files_names <- gsub(x = files_names, pattern = "\\.BLR","",ignore.case = T)
files_names <- gsub(x = files_names, pattern = "\\.","\n",ignore.case = T)


#Extract list of shared regions
output_file <- paste0(file_name,"sample_merged_overlapp.txt")
perl_code <- sprintf( 'perl -ne \'print "$1\\n" if /SUPP_VEC=([^,;]+)/\' %s | sed -e \'s/\\(.\\)/\\1 /g\' > %s',
                      vcf_file, output_file)
system(perl_code)


#Plotting the intersections
t=read.table(output_file ,header=F)

list_to_plot <- list(which(t[,1]==1), which(t[,2]==1), which(t[,3]==1), which(t[,4]==1))
names(list_to_plot) <- files_names

venn.diagram(list_to_plot,
             fill = c("pink", "orange" ,"blue","green") ,
             alpha = c(0.5, 0.5, 0.5, 0.5),
             cex = 2, lty =2, filename =  paste0(file_name,"my_sample_overlapp.gif"),
             );
