name: CI

on:
  push:
   branch:
     - main
  pull_request:
    branch:
      - main
  schedule:
    - cron: 0 7 10 * *

jobs:
  Linting:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
          architecture: x64
      - name: Install flake8
        run:
          pip install flake8
      - name: Run flake8
        run: |
          flake8 src/ tests/
          flake8 --select=W292 --filename '*.yaml,*.yml'

  Testing:
    needs:
      - Linting
    name: Run pipeline
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          environment-file: environment.linux-64.lock
      - name: Install test deps
        run: |
          mamba install pytest
          # Bioconda build for deepvariant no working currently
          # see:
          # - https://github.com/bioconda/bioconda-recipes/issues/30310
          # - https://github.com/nf-core/modules/issues/1754
          # mamba install deepvariant=1.3.0
      - name: Install BLR
        run: pip install .
      - name: Download test dataset
        env:
          testdata_version: "0.7"
        run: |
          wget -nv https://export.uppmax.uu.se/uppstore2018173/blr-testdata-${testdata_version}.tar.gz
          tar xf blr-testdata-${testdata_version}.tar.gz
          ln -s blr-testdata-${testdata_version} blr-testdata
      - name: Run tests
        run: |
          tests/run.sh
