name: CI

on: 
  pull_request:
  schedule:
    - cron: 0 7 * * 1,3,5

jobs:
  run:
    name: Run pipeline
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: testenv
          environment-file: environment.linux-64.lock
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Update env
        run: |
          conda activate testenv
          pip install flake8 pytest
          pip install .
      - name: Env info
        run: |
          conda activate testenv
          conda info
          conda list
          pip list
      - name: Run flake8
        run: |
          conda activate testenv
          flake8 src/ tests/
          flake8 --select=W292 --filename '*.yaml,*.yml'
      - name: Download test dataset
        env:
          testdata_version: "0.6"
        run: |
          wget -nv https://export.uppmax.uu.se/uppstore2018173/blr-testdata-${testdata_version}.tar.gz
          tar xf blr-testdata-${testdata_version}.tar.gz
          ln -s blr-testdata-${testdata_version} blr-testdata
      - name: Run tests
        run: |
          conda activate testenv
          tests/run.sh
