name: CI macos

on:
  workflow_dispatch:

jobs:
  Testing:
    name: Run pipeline
    timeout-minutes: 20
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          use-mamba: true
          channels: conda-forge
          environment-file: environment.osx-64.lock
          use-only-tar-bz2: true
      - name: Install test deps
        run: mamba install pytest
      - name: Install BLR
        run: pip install .
      - name: Run tests
        run: |
          tests/run.sh
